### ISSUE TITLE
Not showing percentage result

### ISSUE THREAD

**Issue by farhansaifi48** [ahfarmer/calculator#11]
Paste below code into calculate.js file
`
if(buttonName === '%') {
   if (obj.next && obj.operation) {
      return {
        total: operate(obj.total, obj.next, '%'),
        next: null,
        operation: null,
      };
    } else {
      // '=' with no operation, nothing to do
      return {};
    } 
  }

`

Issue will be solved and show percentage result
Thanks

**Comment by ahfarmer** [comment]
Thanks for reporting the issue! My original implementation had % sign doing the modulus operation but you're right - it should divide by 100 to match the Mac calculator.

Fixed with https://github.com/ahfarmer/calculator/commit/bc78cfe11ea54c97a19c2c8b597c6997329e595a
