### ISSUE TITLE
Modulus (%) operator is not working with two numbers 

### ISSUE THREAD

**Issue by harvin123** [ahfarmer/calculator#21]
The % operator is always doing operation with 100 only .It should be do operation like other (+,-,/) operators are doing .

Thank you

**Comment by hk-fellow** [comment]
> The % operator is always doing operation with 100 only .It should be do operation like other (+,-,/) operators are doing .
> 
> Thank you

AFAIK, "%" means percent, not modulus. So effectively it divides into 100 and this is expected behavior

**Comment by ahfarmer** [comment]
Good point - closing
