### ISSUE TITLE
Input "." First The Result is not decimals

### ISSUE THREAD

**Issue by ChenLin12138** [ahfarmer/calculator#9]
1. Input AC
2. Input "."
3. Input any number such as 6.
4. The result is not 0.6
It  different from calculator from normal calculator.

**Comment by ahfarmer** [comment]
Thanks for reporting this! Fixed with https://github.com/ahfarmer/calculator/commit/52308b3927ee14e67b89ed31c3800950ecaee6b6

**Comment by ChenLin12138** [comment]
Thanks for you guide me in react.
